#order-service.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: order-service-config
data:
  PORT: "3004"
  MONGODB_URI: "mongodb://mongo:27017/ecommerce_orders"
  CART_SERVICE_URL: "http://cart-service:3003"
  PRODUCT_SERVICE_URL: "http://192.168.65.3:30002"
  USER_SERVICE_URL: "http://user-service:3001"
  #JWT_SECRET: "c154ad5af929569ddbd01761232e9a44bcef5dd709a9e01c2c9c7034b0e9a13d"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: ranyabrkumar/ecom-order-service:latest
          ports:
            - containerPort: 3004
          envFrom:
            - configMapRef:
                name: order-service-config
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  selector:
    app: order-service
  ports:
    - port: 3004
      targetPort: 3004